version: '2'
services:
  web:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=sber